### ISSUE TITLE
I want to learn how to decompile to find offsets

### ISSUE THREAD

**Issue by hzm0603** [roy6307/Goose-Goose-Goose#13]
I found this project yesterday, but it has not been updated, so I want to update it myself, but I am not familiar with Unity. Is there any related tutorial to learn to find these offsets.Or Discard?

**Comment by roy6307** [comment]
First of all, I'm not familiar with Unity too!

I'm using [il2cppDumper](https://github.com/Perfare/Il2CppDumper) and [dnSpy](https://github.com/dnSpy/dnSpy) to find offsets.

1. get DummyDll using il2cppDumper.
2. open Dll files with dnSpy.
3.  For a function, I'm using "RVA". Here's an example.
![fn](https://user-images.githubusercontent.com/36528164/206904865-13e78693-ee8a-4169-92c7-60a2c7e773b7.png)
(Use "0x2AC870". Not "0x0000212A")

4. It's not much difference for fields. Here's an example again.
![fl](https://user-images.githubusercontent.com/36528164/206905115-cd1dfdb5-8730-45af-8f58-ae94ec7d8d46.png)
instance address in memory + Offset = what we want.
If we know the instance address, we can get any fields we want except "static" fields because static variable is not located in instance.

If you have any question, please let me know.
I hope you have a good day! :)
